trigger: none
pr: none


pool:
  name: PoolRunners

variables:
  IMAGE_NAME: 'fouadallaoui/nextjsbaseapp'


steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(NODE_VERSION)
  displayName: 'Install Node.js'

