trigger: none
pr: none


pool:
  name: PoolRunners

variables:
  IMAGE_NAME: 'fouadallaoui/nextjsbaseapp'
  NODE_VERSION: '20.x'

stages:
- stage: PR-Check
  displayName: 'Install-Build-Audit'
  jobs:
  - job: Install-Build-Audit
    displayName: 'Install Dependencies & Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
      displayName: 'Install Node.js'
    
    - script: |
        npm ci
      displayName: 'Clean install'
    
    - script: |
        npm test || echo 'Script not found'
      displayName: 'Test the code'
    
    - script: |
        npm run build --prod
      displayName: 'Build the code'
    
    - script: |
        npm audit --prod
      displayName: 'Audit the code'




